/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package udesc.br.sudoku.gui;

import udesc.br.sudoku.core.*;
import java.util.ArrayList;

/**
 *
 * @author guilhermeutiama
 */
public class inte extends javax.swing.JFrame {

    /**
     * Creates new form inte
     */
//    protected static Level level;
    private ArrayList<javax.swing.JButton> buttons = new ArrayList<>();
    public int nivel;
    protected Generator generator;
    protected InterJogo jogo;

    public inte() {
        this.setTitle("Sudoku");
        initComponents();
        hide_all();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base5 = new javax.swing.JButton();
        base10 = new javax.swing.JButton();
        base17 = new javax.swing.JButton();
        sudokuLabel = new javax.swing.JLabel();
        comboFacil = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        base5.setText("Jogar 4x4");
        base5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                base5ActionPerformed(evt);
            }
        });

        base10.setText("Jogar 9x9");
        base10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                base10ActionPerformed(evt);
            }
        });

        base17.setText("Jogar 16x16");
        base17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                base17ActionPerformed(evt);
            }
        });

        sudokuLabel.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 48)); // NOI18N
        sudokuLabel.setText("Soft Sudoku");

        comboFacil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facil", "Medio", "Dificil" }));
        comboFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFacilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(sudokuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(base5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(base10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(base17, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(comboFacil, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sudokuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(base5)
                    .addComponent(base10)
                    .addComponent(base17))
                .addGap(38, 38, 38)
                .addComponent(comboFacil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void base10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_base10ActionPerformed
        String diff = (String) comboFacil.getSelectedItem();
        if(diff.equals("Facil")){
            setNivel(1);
        }else if(diff.equals("Medio")){
            setNivel(2);
        }else{
            setNivel(3);
        }
        
        generator = new Generator(3, nivel);
        jogo = new InterJogo(generator);
        this.setVisible(false);
        jogo.setVisible(true);
        
    }//GEN-LAST:event_base10ActionPerformed

    private void base5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_base5ActionPerformed
        String diff = (String) comboFacil.getSelectedItem();
        if(diff.equals("Facil")){
            setNivel(1);
        }else if(diff.equals("Medio")){
            setNivel(2);
        }else{
            setNivel(3);
        }
        
        generator = new Generator(2, nivel);
        jogo = new InterJogo(generator);
        this.setVisible(false);
        jogo.setVisible(true);

    }//GEN-LAST:event_base5ActionPerformed

    private void base17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_base17ActionPerformed
        String diff = (String) comboFacil.getSelectedItem();
        if(diff.equals("Facil")){
            setNivel(1);
        }else if(diff.equals("Medio")){
            setNivel(2);
        }else{
            setNivel(3);
        }
        
        generator = new Generator(4, nivel);
        jogo = new InterJogo(generator);
        this.setVisible(false);
        jogo.setVisible(true);
    }//GEN-LAST:event_base17ActionPerformed

    private void comboFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFacilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFacilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inte().setVisible(true);
            }
        });
    }

    protected void hide_all() {
        this.buttons.forEach((button) -> button.setVisible(false));
    }

    void setNivel(int nivel) {
        this.nivel = nivel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton base10;
    private javax.swing.JButton base17;
    private javax.swing.JButton base5;
    private javax.swing.JComboBox<String> comboFacil;
    private javax.swing.JLabel sudokuLabel;
    // End of variables declaration//GEN-END:variables
}
